hashgraph/hedera-accelerator-defi-eip

- contracts/common/HTSToken.sol
- contracts/common/HTSTokenFactory.sol
- data/deployments/chain-296.json
- scripts/deploy.ts
* Split HTSToken and HTSTokenFactory contracts and add both to the deployment script.
> Split HTSToken and HTSTokenFactory contracts

- contracts/erc4626/TokenBalancer.sol
- contracts/erc4626/interfaces/IERC4626.sol
- contracts/erc4626/interfaces/ISaucerSwap.sol
- contracts/erc4626/mocks/MockOracle.sol
- scripts/deployVault.ts
* Add token balancer abstract contract, documentation and update vault deployment.
> Create token balancer

- contracts/erc3643/compliance/modular/modules/MaxOwnershipByCountryModule.sol
- contracts/erc3643/compliance/modular/modules/MaxOwnershipModule.sol
- contracts/erc3643/compliance/modular/modules/MaxTenPercentOwnershipModule.sol
- data/deployments/chain-296.json
- test/erc3643/compliances/module-max-ownership-by-country.test.ts
- test/erc3643/compliances/module-max-ownership.test.ts
- test/erc3643/compliances/module-max-ten-percent-ownership.test.ts
* Removes percentage check from mint function.
> Removes percentage check from mint

- contracts/erc3643/compliance/modular/modules/MaxOwnershipByCountryModule.sol
- contracts/erc3643/compliance/modular/modules/MaxOwnershipModule.sol
- contracts/erc3643/compliance/modular/modules/MaxTenPercentOwnershipModule.sol
- data/deployments/chain-296.json
- test/erc3643/compliances/module-max-ownership-by-country.test.ts
- test/erc3643/compliances/module-max-ownership.test.ts
- test/erc3643/compliances/module-max-ten-percent-ownership.test.ts
* Removes compliance check from mint.
> Removes compliance check from mint.

- .github/workflows/push.yml
- contracts/erc6960/DLT.sol
- contracts/erc6960/TestDLT.sol
- contracts/erc6960/TestDLTWithHTS.sol
- contracts/erc6960/extensions/DLTEnumerable.sol
- contracts/erc6960/extensions/DLTEnumerableWithHTS.sol
- contracts/erc6960/extensions/DLTPermit.sol
- contracts/erc6960/extensions/HTSNonFungibleToken.sol
- contracts/erc6960/interfaces/IDLT.sol
- contracts/erc6960/interfaces/IDLTEnumerable.sol
- contracts/erc6960/interfaces/IDLTPermit.sol
- contracts/erc6960/interfaces/IDLTReceiver.sol
- contracts/erc6960/utils/DLTNonReceiver.sol
- contracts/erc6960/utils/DLTReceiver.sol
- contracts/erc6960/utils/DLTReceiverRevertable.sol
- test/erc6960-hts/DLTWithHTS.test.ts
- test/erc6960-hts/interfaces/IDLTPermit.ts
- test/erc6960/DLT.test.ts
- test/erc6960/DLTPermit.test.ts
- test/erc6960/helpers/eip712.ts
- test/erc6960/interfaces/IDLTPermit.ts
* Adds ERC6960 (Dual Layer Token) contracts and tests
* Adds ERC6960 (Dual Layer Token) With HTS support
> ERC6960 (Dual Layer Token)

- contracts/erc7540/AsyncVault.sol
- contracts/erc7540/interfaces/IERC7540.sol
- scripts/deploy.ts
- scripts/deployVault.ts
- test/erc7540/asyncVault.test.ts
* Adds the implementation of erc7540 with tests.
> implement async vault and add tests

- contracts/erc6960/DLT.sol
- contracts/erc6960/TestDLTERC20.sol
- contracts/erc6960/TestDLTERC20LIFO.sol
- contracts/erc6960/TestDLTERC20RoundRobin.sol
- contracts/erc6960/extensions/DLTERC20FIFO.sol
- contracts/erc6960/extensions/DLTERC20LIFO.sol
- contracts/erc6960/extensions/DLTERC20RoundRobin.sol
- test/erc6960/DLTERC20.test.ts
- test/erc6960/DLTERC20LIFO.test.ts
- test/erc6960/DLTERC20RoundRobin.test.ts
This pull request implements an adaptation of the Dual Layer Token standard (EIP-6960) to support ERC20-compatible transfer and allowance style functions with First-In-First-Out (FIFO) Last-in-First-Out (LIFO) and round-robin strategies for sub-account selection.
- Standard 6960 transactions remain unchanged and function as expected.
- ERC20 compatibility is added, enabling transfer, allowance, and related functionalities.
- A FIFO strategy is employed for sub-account selection during ERC20-style interactions.
- A LIFO strategy is employed for sub-account selection during ERC20-style interactions.
- A round-robin strategy is employed for sub-account selection during ERC20-style interactions.
This update allows the Dual Layer Token to operate seamlessly in ERC20 ecosystems while …
> Dual Layer Token/EIP6960 ERC20 Adaptation

- .github/workflows/push.yml
- .github/workflows/push_main.yml
- .github/workflows/release.yml
Updates per Q3 audit findings
* Related to #26
> ci: Update per Q3 audit findings

- contracts/erc3643/token-dlt/ITokenDLT.sol
- contracts/erc3643/token-dlt/TokenDLT.sol
- contracts/erc3643/token-dlt/TokenDLTStorage.sol
- contracts/erc3643/token-dlt/dlt/DLT.sol
- contracts/erc3643/token-dlt/dlt/extensions/DLTERC20FIFO.sol
- contracts/erc3643/token-dlt/dlt/extensions/DLTEnumerable.sol
- contracts/erc3643/token-dlt/dlt/interfaces/IDLT.sol
- contracts/erc3643/token-dlt/dlt/interfaces/IDLTEnumerable.sol
- contracts/erc3643/token-dlt/dlt/interfaces/IDLTReceiver.sol
- test/erc3643/fixtures/deploy-full-suite-dlt.fixture.ts
- test/erc3643/token-dlt/token-information.test.ts
- test/erc3643/token-dlt/token-recovery.test.ts
- test/erc3643/token-dlt/token-transfer.test.ts
Adds DLT support for tokeny ERC3643 Token contract
> Adds DLT support for tokeny ERC3643 Token contract

- contracts/audit/AuditRegistry.sol
- contracts/buildings/Building.sol
- contracts/buildings/BuildingBase.sol
- contracts/buildings/BuildingFactory.sol
- contracts/buildings/BuildingLiquidityPool.sol
- contracts/buildings/extensions/BuildingAudit.sol
- contracts/buildings/extensions/BuildingLiquidityPool.sol
- contracts/buildings/interface/UniswapInterface.sol
- contracts/buildings/library/BuildingToken.sol
- contracts/buildings/library/CallContract.sol
- contracts/buildings/mock/BuildingFactoryMock.sol
- contracts/buildings/mock/BuildingMock.sol
- contracts/buildings/mock/ERC20Mock.sol
- contracts/erc721/ERC721Metadata.sol
- contracts/erc721/interface/IERC721Metadata.sol
- contracts/uniswap/mock/UniswapFactoryMock.sol
- contracts/uniswap/mock/UniswapRouterMock.sol
- hardhat.config.ts
- package.json
- test/buildings/Building.test.ts
- test/buildings/BuildingFactory.test.ts
- yarn.lock
Adds Building and Building Factory contract as well as Building Liquidity Pool creation.
> Add Building and BuildingFactory with Liquidity Pool

- package.json
**Description**:
Resolve unscoped package accelerator-defi-eip
**Related Issue(s)**:
Fixes #63
> chore (audit): resolve unscoped package

- contracts/buildings/BuildingFactory.sol
- test/buildings/BuildingFactory.test.ts
Adds a function to call whitelisted contracts as the building. 
This enables interacting with the ERC721 metadata contract setting on-chain metadata from the building factory contract.
It can be upgraded later for other purposes. 
Notice that this allows anyone to execute callable contract function as the building until ownership/ACL of BuildingFactory is adjusted
> Call as building

- contracts/buildings/BuildingFactory.sol
- contracts/buildings/library/BuildingToken.sol
- contracts/buildings/mock/BuildingFactoryMock.sol
- data/deployments/chain-296.json
- examples/buildings/create-building-token.ts
- examples/buildings/create-building.ts
- examples/buildings/handle-onchain-metadata.ts
- scripts/deploy.ts
- test/buildings/BuildingFactory.test.ts
* Adds a function to create new ERC3643 (TREX) token for the building
* New deployment addresses
* Examples to interact with building factory
> Building token

- data/deployments/chain-296.json
new deployed address for building factory
> redeploy building factory

- contracts/buildings/BuildingFactory.sol
- contracts/erc4626/interfaces/IRewards.sol
- contracts/treasury/Treasury.sol
- contracts/treasury/VaultMock.sol
- contracts/treasury/interfaces/ITreasury.sol
- test/buildings/Building.test.ts
- test/buildings/BuildingFactory.test.ts
- test/buildings/BuildingGovernance.test.ts
- test/treasury/treasuryTestHardhat.test.ts
Using addReward on treasury to forward excess funds to vault.
Adding vault to treasury after it's deployment.
> Excess funds in Treasury get sent to Vault

- contracts/buildings/governance/BuildingGovernance.sol
- contracts/buildings/governance/BuildingGovernanceStorage.sol
- test/buildings/BuildingFactory.test.ts
- test/buildings/BuildingGovernance.test.ts
Change emitted event on proposal creation to `event ProposalDefined(uint256 id, ProposalType proposalType, address proposer, address receiver, uint256 amount);` to avoid confusion with IGovernor `event ProposalCreated`
This event also adds information on the receiver's address and amount.
> Fix proposal emited event

- contracts/buildings/BuildingFactory.sol
- contracts/buildings/BuildingFactoryStorage.sol
add vault address to building details
> Add vault address to details

- contracts/erc4626/doc/README.md
- contracts/erc7540/doc/README.md
- contracts/erc7540/interfaces/IERC7540.sol
* Adds documentation for ERC4626;
* Adds documentation for ERC7540.
> add documentation for erc4626 and erc7540

- contracts/erc4626/BasicVault.sol
- contracts/erc4626/BasicVaultStorage.sol
- contracts/erc7540/AsyncVault.sol
- contracts/erc7540/AsyncVaultStorage.sol
- contracts/erc7540/ERC7540.sol
- data/deployments/chain-296.json
- examples/vault/deposit.ts
- test/erc4626/basicVault.test.ts
- test/erc7540/asyncVault.test.ts
* Adds namespaced storage for vault.
> add namespaced storage for vault

- contracts/buildings/BuildingFactory.sol
- contracts/buildings/BuildingFactoryStorage.sol
- contracts/buildings/mock/BuildingFactoryMock.sol
- test/buildings/BuildingFactory.test.ts
Replace vault factory for standard vault deployment
> Replace vault factory for standard vault deployment

- contracts/buildings/BuildingFactory.sol
Grant vault reward controller role to treasury
> Grant vault reward controller role to treasury
